### ISSUE TITLE
Track skips when transcoding is enabled

### ISSUE THREAD

**Issue by adjenks** [izderadicka/audioserve#136]
When transcoding is enabled (only tested high setting) the track will skip some time after loading, from 5 to 30 seconds into the song.

It pauses for a moment and replays a fraction of a second of audio and then plays the rest of the track fine.

I'm using this docker container: 594a98a331d6edc398cc4082a9881f24cd3087...

I've tested on Android with Brave and Firefox, and on Ubuntu with Firefox, and they all have this issue.

With transcoding is disabled, it takes a bit longer to load, but there is no skip noise when playing a track.

Thank you for the great software. Keep up the good work.

**Comment by izderadicka** [comment]
Thanks, couple of questions:

1) Do I understand correctly, that it'll skip initial 5-30 seconds of the track/audiofile   from the beginning after starting new file - transcoded? Maybe it'll good to capture this behavior to video? I definitelly do not see it on FF+Ubuntu..
2) What about Chrome/Chromium?  Actually media player in FF and Chrome differs, I found Chrome to usually behave better/more correctly so I prefer it for Audioserve, though otherwise I use Firefox a lot.  
3) What about official demo site https://audioserve.zderadicka.eu/  (secret is mypass)  is it also happenig there?
4) Is it happening for already cached files (circle arrows on list  item and in bottom player)? Or for files transcoded on fly (squeeze icon in bottom player)?

**Comment by adjenks** [comment]
1. No, sorry, at some point near the beginning (between 5 to 30 seconds in), it will sort of pause for a fraction of a second, rewind for a fraction of a second and then continue playing, it just sounds like a small blip. Sort of like 1,2,3,4,5,5,6,7,8... Like you'll hear the same guitar strum twice, it's less than a second.
2. I don't have Chrome, but I tested on Brave, which is derived from Chromium.
3. I tested your demo on Firefox with my android phone, it happens there as well sometimes.
4. It happens on first load of a track while it's starting to cache.

I don't experience it with my own server, or your demo, when browsing on a computer with very fast internet on Firefox on Windows. I'm not sure if it's because the internet is fast, or because it's Windows Firefox.

**Comment by izderadicka** [comment]
Thanks for detailed explanation, I think I understand now  -  I think this is due to the imperfection of  my caching implementation in the browser.  The intent is to get file cached as soon as possible, while also start to play file immediately.
So how does it work, when you start to play uncached file (from beginning, as we want to cache only whole files)
1) File starts to play immediately from live stream
2) In parallel this stream stream is cached as quickly as possible
3) When whole file is cached fully then playback is switched to cached version at the exact moment of current playback.

This can be sometimes audible as  kind of glitch, skip, slide as you described.  
It very much depends on browser, it's resources and audio encoding - so it's more possible that it's more notable on transcoded file as opus is more demanding for decoding then mp3.  
I also hear it sometimes - but for speech it's not so notable, usually small falter, which I consider acceptable for the price feature described above. But for music probably it could be more annoying.

As workaround you can use  Cache current folder from menu and then listened only to cached files. 

Probably I shall make this switching  as an option in preferences.

**Comment by adjenks** [comment]
Yes this makes sense. Thank you for the explanation!
In the meantime I will cache everything first when I can.
Have a great day!

**Comment by izderadicka** [comment]
@adjenks  Lastest version 0.6.0 of client - in master branch of audioserve-web has a fix for this. By default audio is not switch to cached version while playing. Cached version is used later (after pause or long jump our of player cached bytes).
You can try on demo site.

**Comment by adjenks** [comment]
Thank you. Sorry for the delay. I've been using the latest version on docker on my own collection and it seems to have no skip.
There also appears to be no skip on the demo site.
Good work!
I'll bug you again if I notice anything!
