### ISSUE TITLE
New web client requires HTTPS

### ISSUE THREAD

**Issue by srd424** [izderadicka/audioserve#141]
Just a heads up - I finally switched from the old web client to the new, and discovered I can't login over an insecure connection. Poking around a bit, the new client requires `window.crypto.subtle`, whereas the old one has fallback code. Turns out that API is only provided in secure contexts on most browsers:

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle#browser_compatibility

**Comment by izderadicka** [comment]
Thanks for info - I did not realize that because in development localhost is considered secure  context, otherwise I use https.

@srd424 I can return easily fallback to new client, but there is another issue there - service workers are also allowed  in secure context and they are essential for new client - for audio caching - which is probably it's best feature.  But it works without service worker. 

You can try without on http  without authentocation  - start with --no-authentication - you'll see how it works there.

**Comment by izderadicka** [comment]
Added alternative JS SHA256 for insecure contexts, so login works there (in latest master of audioserve-web) in insecure context. However Cache Storage and Service workers are available only in secure context, by browsers design. So caching will not work on http and caching is one of most useful features of client.

**Comment by winhex** [comment]
I use a reverse proxy with https (cloudflare tunnel), local server uses simple http, what should I do in this case?
