### ISSUE TITLE
Allow caching of entire folder

### ISSUE THREAD

**Issue by MagicfTail** [izderadicka/audioserve#41]
Often, simply downloading the entire audiobook instead of having to have a connection to the server all the time is useful, if you know you aren't going to be near a connection all the time.

**Comment by izderadicka** [comment]
Android client contains such functionality,   audioserver also allows to download full folder as .tar archive. 

Caching in web client is quite complex problem -  while there is a Cache API in modern browsers, HTML media player is not working with that, it uses it's own caching.   It'll then probably require to use Web Audio API to use cached content -  I think it's quite complex task in browser. 
For sure it'll require complete rebuild of web client, which is something I'll not do in near future (probably never).   Web client was created as simple front end to start with.  More complex web client is of course possible and probably even desirable, but now lacking time and interest to do that.

**Comment by KodeStar** [comment]
The front end I'm working on allows you to cache all the files.

Currently the way it works is on the overview page there is a download button, if it's pressed all the files are downloaded to Cache API. If the app is installed as a PWA then this cache is persistant, if it's not then it *could* be cleared up, I haven't tested how that will present itself yet. If you don't click the button and start playing, what I'm doing at the moment it downloading the first file putting it in cache, and playing the cached file (no issues with seeking playing the cached file), then when it gets to the next file it downloads that one into cache it and then plays, and so on. The plan is for those files to be cleared up when the book is finished (and to maybe download the next book when it's near the end of the file).

Once that is all working as it should I'll then put back the options to allow transcoding instead of downloading and caching, but that is less important for me.

The one slight wrinkle in that is single file m4b's as you would essentially need to download the whole file to start off with, so I'm not sure how I'm going to deal with that yet. On the current web client the file is essentially cut up into smaller files and streamed.

**Comment by wtanksleyjr** [comment]
Oooh, I missed the .tar download option. Would it be any good to ask for a
per-server option to use uncompressed (-0) .zip format instead? Tar is
almost useless for my use case, but .zip would let me just download the
whole folder and then do whatever with the result.

-Wm

**Comment by izderadicka** [comment]
@wtanksleyjr - current version of audioserve already allows  to download a folder in zip format without compression (that is default now, tar is still possible under program option)

**Comment by izderadicka** [comment]
New client how enables to cache whole folder (similar to Android client). 
Only requirement is to serve client securely so Service Worker is available.
