### ISSUE TITLE
Media With Trailing Spaces Not Accessible

### ISSUE THREAD

**Issue by cryptoluks** [izderadicka/audioserve#50]
Hi,

thanks for developing audioserve, it's exactly the tool I was looking for.

Running `audioserve 0.15.4` in a docker environment without a special custom config.

I accidentally put a trailing space into a folder name, this made the folder inaccessible through the web interface and I jumped right to the start page.

Not a major thing, but anyway, spaces should not break the system, right? :smile: 

Thanks again and have a nice day.

**Comment by izderadicka** [comment]
Yes, I think you right, there are some folder/path names which can cause problems.  
Some characters - like { or >  can cause problems in reverse proxy like nginx,   | or $$ are used for special functions,
and yes I think training spaces are causing problems -   I might look at exact place - but since having trailing space is not good idea anyhow it will not be priority (actually because how path is handled and used in clients probably this should not be allowed anyhow - so question is how to appropriately report the problem).

**Comment by izderadicka** [comment]
Checked problem -  yes trailing space is causing problem in both clients.
Problem seems to be in client - it removes trailing space in URL and then server returns correctly 404 - not found. If entering manually URL with encoded training space ( as %20) server returns correct JSON with folder listing.

**Comment by izderadicka** [comment]
New web client should work fine with folders ending with spaces.
