### ISSUE TITLE
Audioserve android don't support nginx auth

### ISSUE THREAD

**Issue by PrzemekSkw** [izderadicka/audioserve#88]
Hi, I set additional login prompt (Access List) in my Nginx Proxy Manager because only secret is too weak for secure. Problem is that android app don't support that.
Regards.

**Comment by izderadicka** [comment]
shared secret is as secure as you generate it (assuming you are of course using TLS for transport encryption). My view then rather than adding another login, stronger shared secret is better choice. 
Security of audioserve is appropriate for its usecase - personal usage and relatively low criticality of exposed data.

That said if you see any real security vulnerability please share on audioserve main repo.

I assume problem here is with http authentication, which will not work in Android client and I do not have any plans now to fix it.

Rather I was focusing on modern PWA web client, which should work well on mobile, so you may try this. Is there still  some critical functionality that new PWA client is missing?

**Comment by PrzemekSkw** [comment]
Hi, thanks for answer. Can You tell me how to generate strong secret?
I use SSL connection on main duckdns domain with Nginx Proxy Manager.
regards.

**Comment by izderadicka** [comment]
On linux you can try something like:
```
cat /dev/urandom | head -c 32 | base64 | tr -d =
```

This will give you 32 random bytes in base64 encoding.
